# Strata Game Publishing Action
# 
# This action provides standardized publishing for Strata-powered games.
# It handles building, testing, and deploying games to GitHub Pages.
#
# Usage:
#   - uses: strata-game-library/capacitor-plugin/.github/actions/strata-game-publish@main
#     with:
#       game-name: otter-river-rush
#       package-manager: pnpm

name: 'Strata Game Publish'
description: 'Build, test, and deploy Strata-powered games to GitHub Pages'
author: 'jbcom'

branding:
  icon: 'play'
  color: 'blue'

inputs:
  game-name:
    description: 'Name of the game (used for deployment URL)'
    required: true
  
  package-manager:
    description: 'Package manager to use (pnpm, npm, yarn)'
    required: false
    default: 'pnpm'
  
  node-version:
    description: 'Node.js version'
    required: false
    default: '22'
  
  build-command:
    description: 'Build command to run'
    required: false
    default: 'build'
  
  dist-path:
    description: 'Path to built assets'
    required: false
    default: 'dist'
  
  run-tests:
    description: 'Whether to run tests before deploying'
    required: false
    default: 'true'
  
  test-command:
    description: 'Test command to run'
    required: false
    default: 'test'

outputs:
  deployment-url:
    description: 'URL where the game is deployed'
    value: ${{ steps.deploy.outputs.page_url }}
  
  build-success:
    description: 'Whether the build succeeded'
    value: ${{ steps.build.outputs.success }}

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      if: inputs.package-manager == 'pnpm'
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.package-manager }}

    - name: Install dependencies
      shell: bash
      run: |
        if [ "${{ inputs.package-manager }}" = "pnpm" ]; then
          pnpm install --frozen-lockfile
        elif [ "${{ inputs.package-manager }}" = "yarn" ]; then
          yarn install --frozen-lockfile
        else
          npm ci
        fi

    - name: Run tests
      if: inputs.run-tests == 'true'
      shell: bash
      run: |
        if [ "${{ inputs.package-manager }}" = "pnpm" ]; then
          pnpm run ${{ inputs.test-command }}
        elif [ "${{ inputs.package-manager }}" = "yarn" ]; then
          yarn ${{ inputs.test-command }}
        else
          npm run ${{ inputs.test-command }}
        fi

    - name: Build
      id: build
      shell: bash
      run: |
        if [ "${{ inputs.package-manager }}" = "pnpm" ]; then
          pnpm run ${{ inputs.build-command }}
        elif [ "${{ inputs.package-manager }}" = "yarn" ]; then
          yarn ${{ inputs.build-command }}
        else
          npm run ${{ inputs.build-command }}
        fi
        echo "success=true" >> $GITHUB_OUTPUT
      env:
        VITE_BASE_URL: /${{ inputs.game-name }}/

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ inputs.dist-path }}

    - name: Deploy to GitHub Pages
      id: deploy
      uses: actions/deploy-pages@v4
